"""The boundary helpers for comparing identities, and the rules for each kind.

Phase 6A found that the protected-holdout guard compared a raw external
product string against a canonical internal one. Twelve of thirteen spellings
of a reserved instrument reported *not protected*. The bug was not clever; it
was a `in` on two things that looked like strings and were not the same kind
of thing.

This module exists so that the *kind* is explicit at every boundary. There are
five, and they have different rules:

**A -- semantic identity.** Instrument, venue, provider, timeframe. Has a
canonical form and a parser. External input is parsed and canonicalised
*before* any comparison. Aliases are welcome; raw comparison is not.

**B -- opaque identity.** SHA-256 digests: spec hashes, result hashes, fitted
hashes, event hashes. Matched byte-exactly and never normalised. Lowercasing
a digest to be helpful would accept a value the producing contract never
emitted, and the whole point of a digest is that only one string is right.

**C -- display label.** Human text. Never compared for identity at all.

**D -- legacy identity.** The bare ``BTC-USD`` written into every committed
artefact and every recorded event. It cannot be rewritten -- the hashes exist
precisely so it cannot -- so it is reached through an adapter that resolves a
semantic identity down to it.

**E -- runtime instance identity.** Session ids. Opaque, generated locally,
never normalised, never used to build a filesystem path.

The asymmetry is deliberate: being liberal about *recognising* an instrument
is what makes the guard safe, and being liberal about recognising a digest is
what makes an integrity check meaningless.
"""

from __future__ import annotations

import re

IDENTITY_SCHEMA_VERSION = "trading-lab.identity-boundary.v1"

# Class B. Exactly what the producing code emits: lowercase hex, 64 chars.
# \Z, not $: in Python `$` also matches immediately before a final newline,
# so "^[0-9a-f]{64}$" accepts "<digest>\n" as a digest. For an identity that is
# supposed to be byte-exact that is precisely the wrong kind of generosity.
_DIGEST_PATTERN = re.compile(r"^[0-9a-f]{64}\Z")
# Class E. Generated by this project; nothing else is accepted.
_SESSION_ID_PATTERN = re.compile(
    r"^paper-\d{8}T\d{6}Z\Z|^[A-Za-z0-9][A-Za-z0-9_-]{0,63}\Z")


class IdentityError(RuntimeError):
    """Raised when two identities cannot be shown to be the same."""


class InstrumentMismatchError(IdentityError):
    """Raised when one instrument's data would be used as another's."""


# --- class A: semantic identities -----------------------------------------


def resolve_instrument(value, *, context: str = "instrument"):
    """Any accepted spelling to the registered specification, or refuse.

    Fail-closed by construction: an unregistered or unparseable value raises
    rather than falling back to a default, the first registry entry, or the
    instrument the caller probably meant.
    """
    from scripts.trading_lab.instrument_registry import INSTRUMENTS_V1, RegistryError

    try:
        return INSTRUMENTS_V1.resolve(value)
    except RegistryError as error:
        raise IdentityError(f"{context}: {error}") from error


def resolve_legacy_product(value, *, context: str = "product") -> str:
    """A semantic identity down to the bare string artefacts are keyed by.

    This is the class D adapter. It is the only sanctioned way to turn
    ``coinbase:BTC-USD`` or ``btc-usd`` into the ``BTC-USD`` that a committed
    manifest or a recorded event uses.
    """
    return resolve_instrument(value, context=context).legacy_product_id


def same_instrument(left, right) -> bool:
    """Do two spellings name the same registered market?

    False when either side cannot be resolved -- unknown is never equal to
    anything, including another unknown.
    """
    try:
        return (resolve_instrument(left).instrument_id
                == resolve_instrument(right).instrument_id)
    except IdentityError:
        return False


def require_same_instrument(left, right, *, context: str,
                            left_label: str = "left",
                            right_label: str = "right"):
    """Refuse unless both name the same market. Returns the specification.

    The error names both sides, because the failure this prevents -- one
    instrument's prices applied to another's decisions -- produces a result
    that looks entirely plausible and is entirely wrong.
    """
    try:
        first = resolve_instrument(left, context=f"{context}/{left_label}")
        second = resolve_instrument(right, context=f"{context}/{right_label}")
    except IdentityError as error:
        raise InstrumentMismatchError(
            f"{context}: cannot establish identity ({error})") from error
    if first.instrument_id != second.instrument_id:
        raise InstrumentMismatchError(
            f"{context}: {left_label} is {first.canonical_id} but {right_label} "
            f"is {second.canonical_id}; refusing to use one instrument's data "
            "as another's")
    return first


# --- class B: opaque identities -------------------------------------------


def require_exact_digest(value: object, *, field: str) -> str:
    """A SHA-256 digest, byte-exact. No case folding, no stripping.

    Normalising here would accept a digest the producing contract never wrote.
    A caller that has an uppercase or padded digest has a bug upstream, and
    quietly repairing it hides that bug behind a check that then proves
    nothing.
    """
    if not isinstance(value, str):
        raise IdentityError(f"{field} must be a hex digest string, "
                            f"got {type(value).__name__}")
    if not _DIGEST_PATTERN.match(value):
        raise IdentityError(
            f"{field} is not a canonical lowercase hex sha256 digest: {value!r}")
    return value


def digests_match(left: object, right: object, *, field: str) -> bool:
    """Exact comparison of two validated digests."""
    return require_exact_digest(left, field=field) == \
        require_exact_digest(right, field=f"{field} (expected)")


def require_matching_digest(actual: object, expected: object, *, field: str) -> str:
    if not digests_match(actual, expected, field=field):
        raise IdentityError(f"{field} does not match the expected digest")
    return actual


# --- class B: protocol and schema versions --------------------------------


def require_exact_protocol(value: object, expected, *, field: str) -> str:
    """A protocol or schema version, matched exactly against a closed set.

    Not normalised. ``"V2"``, ``" v2 "`` and ``"v02"`` are not spellings of
    ``"v2"`` -- they are values nobody agreed to emit. A protocol identity is
    a contract, not a user-facing alias, and an unknown one fails closed.
    """
    allowed = (expected,) if isinstance(expected, str) else tuple(expected)
    if not isinstance(value, str):
        raise IdentityError(f"{field} must be a string, got {type(value).__name__}")
    if value not in allowed:
        raise IdentityError(
            f"{field} {value!r} is not a known protocol version; expected one "
            f"of {list(allowed)}")
    return value


# --- class E: runtime instance identities ---------------------------------


def require_session_id(value: object, *, field: str = "session_id") -> str:
    """A locally generated run identifier. Validated, never normalised.

    Checked because a session id reaches a database and could one day reach a
    filename. It is deliberately *not* canonicalised: two sessions differing
    only in case are two different runs, and folding them would merge two
    histories.
    """
    if not isinstance(value, str) or not value:
        raise IdentityError(f"{field} must be a non-empty string")
    if len(value) > 64:
        raise IdentityError(f"{field} is longer than 64 characters")
    if not _SESSION_ID_PATTERN.match(value):
        raise IdentityError(
            f"{field} {value!r} is not a usable session identifier")
    if "/" in value or "\\" in value or ".." in value or "\x00" in value:
        raise IdentityError(f"{field} must never contain a path separator")
    return value


__all__ = [
    "IDENTITY_SCHEMA_VERSION", "IdentityError", "InstrumentMismatchError",
    "digests_match", "require_exact_digest", "require_exact_protocol",
    "require_matching_digest", "require_same_instrument", "require_session_id",
    "resolve_instrument", "resolve_legacy_product", "same_instrument",
]
